System.out.println("Opción 1. Cargar 100 trabajadores");
            System.out.println("Opción 2. Ingresar un trabajador por horas");
            System.out.println("Opción 3. Ingresar trabajador por comisión");
            System.out.println("Opción 4. Ingresar trabajador asalariado");
            System.out.println("Opción 5. Calcular el salario de un trabajador");
            System.out.println("Opción 6. Calcular la nómina de todos los trabajores");
            System.out.println("Opción 7. Eliminar a un trabajador por su nombre");
            System.out.println("Opción 8. Eliminar a un trabajador por su posición");
            System.out.println("Opción 9. Buscar trabajadores que ganen mas que x");
            System.out.println("Opción 10. Buscar trabajadores que ganen menos que x");
            System.out.println("Opción 11. Buscar al trabajador que gane mas de todos los");
            System.out.println("Opción 12. Buscar al trabajador que gana menos dinero");
            System.out.println("Opción 13. Buscar a un trabajador por apellido x");
            System.out.println("Opción 14. Buscar a un trabajador que tenga 2 apellidos iguales");
            System.out.println("Opción 15. Buscar a un trabajador por su nombre x");
            System.out.println("Opción 16. Buscar a un trabajador que sea mayor de una edad x");
            System.out.println("Opción 17. Buscar a un trabajador que sea menor de una edad x");
            System.out.println("Opción 18. Buscar a un trabajador que vivan en la calle x");
            System.out.println("Opción 19. Buscar a un trabajador que vivan en la colonia x");
            System.out.println("Opción 20. Buscar a un trabajador que que viva en la casa numero x");
            System.out.println("Opción 21. Salir del programa");